#!/bin/bash
FILE=/home/$USER/.indicator-chars
TMP=$(mktemp)
zenity --text-info --editable --title="Edit user configuration file" --filename=$FILE > $TMP
    if [ "$?" = 0 ]; then
		mv $FILE "$FILE"~
    	mv $TMP "$FILE"
		notify-send "Saved indicator-chars user config" -i gtk-dialog-info -t 3000 -u normal
	fi
exit 0