#!/bin/bash
sudo mkdir -p '/usr/local/indicator-chars'
sudo cp './indicator-chars.py' '/usr/local/indicator-chars/indicator-chars.py'
sudo chown root:root '/usr/local/indicator-chars/indicator-chars.py'
sudo ln -sf '/usr/local/indicator-chars/indicator-chars.py' '/usr/local/bin/indicator-chars.py'
sudo chmod 755 '/usr/local/indicator-chars/indicator-chars.py'
sudo cp './dark-theme-icon.sh' '/usr/local/indicator-chars/dark-theme-icon.sh'
sudo chown root:root '/usr/local/indicator-chars/dark-theme-icon.sh'
sudo chmod a+x '/usr/local/indicator-chars/dark-theme-icon.sh'
sudo cp './light-theme-icon.sh' '/usr/local/indicator-chars/light-theme-icon.sh'
sudo chown root:root '/usr/local/indicator-chars/light-theme-icon.sh'
sudo chmod a+x '/usr/local/indicator-chars/light-theme-icon.sh'
sudo cp './dark-theme.png' '/usr/local/indicator-chars/dark-theme.png'
sudo cp './light-theme.png' '/usr/local/indicator-chars/light-theme.png'
sudo cp './indicator-chars.png' '/usr/local/indicator-chars/indicator-chars.png'
sudo chmod a+r '/usr/local/indicator-chars/dark-theme.png'
sudo chmod a+r '/usr/local/indicator-chars/light-theme.png'
sudo chmod a+r '/usr/local/indicator-chars/indicator-chars.png'
sudo cp './indicator-chars.desktop' '/etc/xdg/autostart/indicator-chars.desktop'
sudo chmod a+rx '/etc/xdg/autostart/indicator-chars.desktop'
